services:
  _defaults:
    autowire: true
    autoconfigure: true
  Customer\:
    resource: '../../src/Customer/'
    exclude:
      - '../../src/Customer/Domain/Model/'
      - '../../src/Kernel.php'
      - '../../src/Tests/'
  Customer\Infrastructure\Controller\Customer\:
    resource: '../../src/Customer/Infrastructure/Controller/Customer/'
    tags: ['controller.service_arguments']