customer_health_check:
  path: /health-check
  controller: Customer\Adapter\Framework\Http\Controller\HealthCheckController
  methods: [ GET ]

create_customer:
  path: /create
  controller: Customer\Adapter\Framework\Http\Controller\Customer\CreateCustomerController
  methods: [ POST ]

get_customer_by_id:
  path: /{id}
  controller: Customer\Adapter\Framework\Http\Controller\Customer\GetCustomerByIdController
  methods: [ GET ]