on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: app checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull docker-compose
        run: docker-compose -f docker-compose.yml.dist pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: copy .env for testing
        run: cp -n .env.test .env.local
      - name: Prepare containers
        run: make start && make prepare
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Run tests
        run: make migrations-test && make tests